services:
  python:       
    build: 
      dockerfile: ./docker/Dockerfile-prod
      context: ./
    image: cdalldorf/my_project_python:latest
    
    # uncomment the below two lines if you plan on running via docker-compose in production
    #env_file: 
    #  - .env_prod

    # add code to be run here
    command: 
      python /code/1_test.py

    # note - once in production I usually pull from an API or some other location, if you
    # still expect to pull data from the file system then uncomment the below two lines and
    # replace /real_data_location with the correct path
    volumes: # may want to replace ./data:/data with /real_data_location:/data, not sure how to best handle this now
      - ./data:/data
      - ./output:/output