services:
  jupyter:
    build: 
      dockerfile: ./docker/Dockerfile-dev
      context: ./
    image: cdalldorf/my_project_python:latest
    ports:
      - "8888:8888"
    command: jupyter lab --no-browser --ip=0.0.0.0 --port=8888 --allow-root --ServerApp.token='local'
    volumes:
      - ./data:/data
      - ./code:/code
      - ./notebooks:/notebooks
      - ./output:/output

  shell:
    image: cdalldorf/my_project_python:latest
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
      - ./code:/code
      - ./notebooks:/notebooks
      - ./output:/output